### ISSUE TITLE
Portfolio Peer Review

### ISSUE THREAD

**Issue by nep2ne** [libecap/portfolio#10]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | **Wow! I never would have thought that would work so well!** |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** |
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |
Sum the rubric and put that value at the bottom.

**15/15**
I confirm that I think this is an appropriate grade for the project I just reviewed.

I totally love the look and feel of your website. It really shows your personality. The mockups are well presented and I like how you treated the sketches at the bottom of the page.

The idea to a) make your isometric design a gig poster and b) place it in a mockup in a real environment is SUPER cool. So is the motion piece you included. I like that the work you show is both diverse and focused. You chose a few key pieces that are really well executed and at the same time show your range. It all works really well. Great idea to promote the Grad Show as well. One thing I would be careful about is the yellow hover highlight & accessibility-- one thing you could do is keep the yellow hover highlight, but when the button is hovered, the text on top also changes colour to black so that it really stands out against the yellow. It would be pretty simple to do -- just add a color: #000 to your hover state in css. Overall super well done. Though I miss the polaroid! It was so cool!

**Comment by libecap** [comment]
Thanks G! I made those changes and I agree, its much more legible.  I miss the polaroid and sticky notes too but I couldn't figure out how to use them without distracting from my portfolio piece. :(
